export const identityCopy = {
  preferNotToSay: "Prefer not to say",
  woman: "Woman",
  man: "Man",
  enterANameWithAtLeast2Characters: "Enter a name with at least 2 characters.",
  use80CharactersOrFewer: "Use 80 characters or fewer.",
  useAtLeast3Characters: "Use at least 3 characters.",
  use24CharactersOrFewer: "Use 24 characters or fewer.",
  useLettersNumbersAndUnderscoresOnly: "Use letters, numbers and underscores only.",
  use254CharactersOrFewer: "Use 254 characters or fewer.",
  enterAValidEmailAddress: "Enter a valid email address.",
  enter7To15DigitsWithAnOptionalSpaces: "Enter 7 to 15 digits, with an optional +, spaces, brackets or hyphens.",
  keepYourBioTo500Characters: "Keep your bio to 500 characters.",
  use100CharactersOrFewer: "Use 100 characters or fewer.",
  chooseEachInterestOnlyOnce: "Choose each interest only once.",
  chooseAnImageNoLargerThan1MB: "Choose an image no larger than 1 MB.",
  chooseAPNGJPEGGIFOrWebPImage: "Choose a PNG, JPEG, GIF or WebP image.",
  enterARealDateWithinTheLast120Years: "Enter a real date within the last 120 years, not in the future.",
  useAtLeast8Characters: "Use at least 8 characters.",
  use128CharactersOrFewer: "Use 128 characters or fewer.",
  includeAtLeastOneNumber: "Include at least one number.",
  pickAtLeastTwoInterestsToContinue: "Pick at least two interests to continue.",
  theFileContentsMustMatchAPNGJPEGGIF: "The file contents must match a PNG, JPEG, GIF or WebP image. SVG and renamed files are not supported.",
  theImageCouldNotBeReadPleaseChooseIt: "The image could not be read. Please choose it again.",
  imageLoadingWasInterruptedPleaseTryAgain: "Image loading was interrupted. Please try again.",
  theImageCouldNotBeRead: "The image could not be read.",
  thisImageIsEmptyChooseAnotherImage: "This image is empty. Choose another image.",
  thisImageIsDamagedOrUnsupportedChooseAnotherImage: "This image is damaged or unsupported. Choose another image.",
  bringingPeopleTogetherOneConnectAtATime: "Bringing people together, one Connect at a time.",
  aMemberOfTheConnectCommunity: "A member of the Connect community.",
} as const
