export const identityFieldsCopy = {
  gender: "Gender",
  dateOfBirthOptional: "Date of birth (optional)",
  notShared: "Not shared",
  formatAge: (age: string | number) => "" + String(age) + " years old",
  notProvided: "Not provided",
  preferNotToSay: "Prefer not to say",
  onlyYourAgeNeverYourBirthDateCanAppear: "Only your age, never your birth date, can appear on your public profile.",
  yourAgeIsNotSharedOrUsedForEligibility: "Your age is not shared or used for eligibility. Turn off Prefer not to say to use your date of birth for age-restricted Connects.",
  withoutADateOfBirthYouCannotJoinAge: "Without a date of birth you cannot join age-restricted Connects. They still appear in Discover; add a date later to check your eligibility.",
  showMyGenderOnMyProfile: "Show my gender on my profile",
  showMyAgeOnMyProfile: "Show my age on my profile",
  ageVisibilityHint: "Only your age is shown, never your date of birth.",
  showMyEmailOnMyProfile: "Show my email on my profile",
  emailVisibilityHint: "Group chat does not need a public email address.",
  showMyPhoneNumberOnMyProfile: "Show my phone number on my profile",
  phoneVisibilityHint: "Share a number only if you want it on the public preview.",
  withheldHidden: "Withheld - hidden",
  notProvidedHidden: "Not provided - hidden",
  visibleOnYourPublicProfile: "Visible on your public profile",
  hiddenFromYourPublicProfile: "Hidden from your public profile",
  interests: "Interests",
  checkmarkSymbol: "\u2713",
  selected: " selected ",
  middleDotSeparator: "\u00b7",
  pickAtLeastTwoForAUsefulFeed: " pick at least two for a useful feed.",
  theImageCouldNotBeLoadedPleaseTryAnother: "The image could not be loaded. Please try another image.",
  profile: "profile",
  photo: "photo",
  uploadAProfilePhoto: "Upload a profile photo",
  loadingPhoto: "Loading photo...",
  changePhoto: "Change photo",
  uploadAPhoto: "Upload a photo",
  removePhoto: "Remove photo",
  optionalChooseAPNGJPEGGIFOrWebPImage: "Optional. Choose a PNG, JPEG, GIF or WebP image up to 1 MB.",
  readingAndCheckingImageContents: "Reading and checking image contents.",
  defaultRadius: "Default radius",
  kilometersSuffix: " km",
  text1Km: "1 km",
  walkable: "Walkable",
  text100Km: "100 km",
  savedWithSignupOrProfileChangesDiscoverUsesThis: "Saved with signup or profile changes. Discover uses this radius unless you choose a different distance there.",
  genderAgeAndContactDetailsAreHidden: "Gender, age and contact details are hidden.",
} as const
