export const profilePageCopy = {
  chooseAReason: "Choose a reason.",
  harassment: "Harassment",
  spamOrScam: "Spam or scam",
  inappropriateContent: "Inappropriate content",
  safetyConcern: "Safety concern",
  other: "Other",
  chooseAListedReason: "Choose a listed reason.",
  use1000CharactersOrFewer: "Use 1,000 characters or fewer.",
  addAtLeast10CharactersSoTheReasonIs: "Add at least 10 characters so the reason is clear.",
  report: (name: string | number) => "Report " + String(name) + "",
  chooseAReasonAndAddAnyDetailsThatHelp: "Choose a reason and add any details that help explain what happened.",
  reportSaved: "Report saved.",
  reason: "Reason",
  chooseAReason2: "Choose a reason",
  reason2: "reason",
  whatHappened: "What happened?",
  additionalDetailsOptional: "Additional details (optional)",
  saveReport: "Save report",
  cancel: "Cancel",
  photoLoadingWasCancelledWhenYouOpenedThePublic: "Photo loading was cancelled when you opened the public preview. Choose the photo again to add it.",
  profileSaved: "Profile saved.",
  yourDetails: "Your details",
  onlyYouSeeThisPanel: "Only you see this panel",
  genderAgeEmailAndPhoneStayOffYourPublic: "Gender, age, email and phone stay off your public profile unless you switch them on below. Name, bio, photo, neighbourhood and interests are public.",
  editYourProfile: "Edit your profile",
  preferNotToSay: "Prefer not to say",
  email: "Email",
  changingYourEmailResetsItsVisibilityToHidden: "Changing your email resets its visibility to hidden.",
  phoneOptional: "Phone (optional)",
  neighbourhoodOrCityOptional: "Neighbourhood or city (optional)",
  whatOtherPeopleCanSee: "What other people can see",
  editNameBioPhotoAndInterests: "Edit name, bio, photo and interests",
  fullName: "Full name",
  username: "Username",
  separator: (username: string | number) => "@" + String(username) + "",
  bioOptional: "Bio (optional)",
  whatBringsYouHere: "What brings you here?",
  text500Characters: "/500 characters",
  pleaseCorrectTheHighlightedFieldsBeforeSaving: "Please correct the highlighted fields before saving.",
  saveChanges: "Save changes",
  unsavedChangesDiscardedYourSavedProfileIsUnchanged: "Unsaved changes discarded. Your saved profile is unchanged.",
  discardChanges: "Discard changes",
  unsavedChanges: "Unsaved changes",
  middleDotSeparator: "\u00b7",
  went: (attendeeCount: string | number) => "" + String(attendeeCount) + " went",
  no: "No ",
  toShowYet: " to show yet.",
  everyone: "Everyone",
  textSeparator: "\u2014",
  attendanceRate: "Attendance rate",
  memberRating: "Member rating",
  connectsHosted: "Connects hosted",
  connectsJoined: "Connects joined",
  yourProfile: "Your profile",
  someoneElseS: "Someone else's",
  noProfilePhotoFor: (name: string | number) => "No profile photo for " + String(name) + "",
  profile: "profile",
  photo: "photo",
  usernamePrefix: "@",
  separator5: (location: string | number) => " \u00b7 " + String(location) + "",
  noBioYet: "No bio yet.",
  editProfile: "Edit profile",
  privacySettings: "Privacy settings",
  backToEditing: "Back to editing",
  previewPublicProfile: "Preview public profile",
  viewConnects: "View Connects",
  report2: "Report",
  memberUnblockedPreviousAttendanceAndRequestsHaveNotBeen: "Member unblocked. Previous attendance and requests have not been restored.",
  unblockMember: "Unblock member",
  blockMember: "Block member",
  countsReflectVisibleConnectActivity: "Counts reflect visible Connect activity.",
  memberBlocked: "Member blocked",
  sharedAttendancePendingRequestsAndPrivateLocationAccessWere: "Shared attendance, pending requests and private-location access were removed. Unblocking does not rejoin any Connect.",
  publicProfilePreview: "Public profile preview",
  thisIsYourSavedProfileAsAnotherMemberWould: "This is your saved profile as another member would see it. Private editing fields have been removed from this view. Unsaved edits are kept for when you return.",
  badges: "Badges",
  starSymbol: "\u2605",
  reliableHost: " Reliable host",
  diamondSymbol: "\u25c6",
  hosted: " hosted",
  newToConnect: "New to Connect",
  pastConnects: "Past Connects",
  upcomingConnects: "Upcoming Connects",
  block: (name: string | number) => "Block " + String(name) + "?",
  thisRemovesYouFromThisMemberSConnectsAnd: "This removes you from this member's Connects and removes them from yours, including pending requests and private-location access.",
  youCanUnblockLaterButAttendanceAndRequestsWill: "You can unblock later, but attendance and requests will not be restored.",
  memberBlocked2: "Member blocked.",
  noProfileYet: "No profile yet",
  memberNotFound: "Member not found",
  backToDiscover: "Back to Discover",
  createAProfileOrSignInToSeeYour: "Create a profile or sign in to see your details.",
  thisProfileIsUnavailable: "This profile is unavailable.",
} as const
