export const signupPageCopy = {
  whoYouAre: "Who you are",
  whatShouldWeCallYou: "What should we call you?",
  yourNameShowsOnConnectsYouHostAndJoin: "Your name shows on Connects you host and join. Your username is how people find you.",
  account: "Account",
  emailAndAPassword: "Email and a password",
  addYourEmailAndChooseAPassword: "Add your email and choose a password.",
  aboutYou: "About you",
  aCoupleOfDetails: "A couple of details",
  youChooseWhichDetailsToShareOnYourProfile: "You choose which details to share on your profile.",
  photo: "Photo",
  addAProfilePhoto: "Add a profile photo",
  optionalButItHelpsHostsRecogniseYouAtThe: "Optional, but it helps hosts recognise you at the meeting point.",
  interests: "Interests",
  whatDoYouWantToDo: "What do you want to do?",
  pickTheCategoriesYouCareAboutTheyShapeYour: "Pick the categories you care about. They shape your feed, and you can change them later.",
  whereYouAre: "Where you are",
  whereShouldWeLook: "Where should we look?",
  addYourNeighbourhoodOrCityOrLeaveItBlank: "Add your neighbourhood or city, or leave it blank.",
  done: "Done",
  readyToGo: "Ready to go",
  reviewYourPublicProfileThenFinishToSaveYour: "Review your public profile, then finish to save your changes.",
  pleaseCorrectTheHighlightedFieldsBeforeFinishing: "Please correct the highlighted fields before finishing.",
  profileSaved: "Profile saved.",
  thisBrowserDoesNotSupportLocationAccessEnterA: "This browser does not support location access. Enter a neighbourhood or city below, or continue without a location.",
  waitingForBrowserPermissionYouCanUseTheManual: "Waiting for browser permission. You can use the manual field or continue without location.",
  locationPermissionGrantedAddANeighbourhoodOrCityBelow: "Location permission granted. Add a neighbourhood or city below, or continue without a location.",
  locationPermissionWasDeniedYouCanAllowItIn: "Location permission was denied. You can allow it in your browser site settings and retry, enter a neighbourhood below, or continue without location.",
  yourLocationCouldNotBeRetrievedRetryEnterA: "Your location could not be retrieved. Retry, enter a neighbourhood below, or continue without location.",
  makeYourselfAtHome: "Make yourself at home",
  step: "Step ",
  of7: " of 7",
  signupProgress: "Signup progress",
  colonSeparatorWithSpace: ": ",
  completed: ", completed",
  middleDotSeparator: "\u00b7",
  signupStep: (stepNumber: string | number) => "Signup step " + String(stepNumber) + "",
  fullName: "Full name",
  noaBerkovich: "Noa Berkovich",
  username: "Username",
  usernamePrefix: "@",
  noab: "noab",
  text324LettersNumbersOrUnderscores: "3-24 letters, numbers or underscores.",
  email: "Email",
  youExampleCom: "you@example.com",
  yourEmailIsHiddenFromYourPublicProfileBy: "Your email is hidden from your public profile by default.",
  password: "Password",
  atLeast8Characters: "At least 8 characters",
  use8CharactersOrMoreWithANumber: "Use 8 characters or more, with a number.",
  preferNotToSay: "Prefer not to say",
  phoneOptional: "Phone (optional)",
  phoneNumber: "Phone number",
  waitingForPermission: "Waiting for permission...",
  retryLocationAccess: "Retry location access",
  allowLocationAccess: "Allow location access",
  youCanAlsoEnterANeighbourhoodOrCityBelow: "You can also enter a neighbourhood or city below.",
  orTypeIt: "or type it",
  neighbourhoodOrCityOptional: "Neighbourhood or city (optional)",
  neighbourhoodOrCity: "Neighbourhood or city",
  finishSignup: "Finish signup",
  youReReady: "You're ready, ",
  sentenceEnding: ".",
  interests3: " interests",
  noLocationNeeded: ", no location needed",
  yourProfileIsReadyToSave: ". Your profile is ready to save.",
  finishAndContinue: "Finish and continue",
  startBrowsing: "Start browsing",
  hostAConnect: "Host a Connect",
  publicProfilePreview: "Public profile preview",
  separator5: (value: string | number) => " \u00b7 " + String(value) + "",
  hiddenDetailsAreNotShownOnYourPublicProfile: "Hidden details are not shown on your public profile. You can edit your details and visibility later.",
  back: "Back",
  reviewProfile: "Review profile",
  continue: "Continue",
  skipForNow: "Skip for now",
  commaSeparatorWithSpace: ", ",
} as const
