export const catalogCopy = {
  sports: "Sports",
  separator: "\u25cf",
  gaming: "Gaming",
  separator2: "\u25a0",
  social: "Social",
  separator3: "\u25c6",
  outdoors: "Outdoors",
  separator4: "\u25b2",
  artsCulture: "Arts & Culture",
  separator5: "\u2733",
  learnMake: "Learn & Make",
  separator6: "\u2726",
  wellness: "Wellness",
  separator7: "\u25d1",
  familyKids: "Family & Kids",
  separator8: "\u271a",
  other: "Other",
  separator9: "\u25cb",
  footballSoccer: "Football/Soccer",
  basketball: "Basketball",
  volleyball: "Volleyball",
  tennisPadel: "Tennis/Padel",
  running: "Running",
  cycling: "Cycling",
  swimming: "Swimming",
  climbing: "Climbing",
  pC: "PC",
  console: "Console",
  boardGames: "Board games",
  tabletopRPG: "Tabletop RPG",
  cardGames: "Card games",
  arcadeLAN: "Arcade/LAN",
  movieNight: "Movie night",
  barCrawl: "Bar crawl",
  houseParty: "House party",
  karaoke: "Karaoke",
  dinnerPotluck: "Dinner/Potluck",
  coffeeMeetup: "Coffee meetup",
  hiking: "Hiking",
  beach: "Beach",
  picnic: "Picnic",
  camping: "Camping",
  dogWalk: "Dog walk",
  liveMusic: "Live music",
  museums: "Museums",
  theater: "Theater",
  photographyWalk: "Photography walk",
  crafts: "Crafts",
  languageExchange: "Language exchange",
  studyGroup: "Study group",
  codingHackNight: "Coding/Hack night",
  workshops: "Workshops",
  bookClub: "Book club",
  yoga: "Yoga",
  gymSession: "Gym session",
  meditation: "Meditation",
  groupWalk: "Group walk",
  playgroundMeetup: "Playground meetup",
  kidsSports: "Kids' sports",
  familyOuting: "Family outing",
  anythingElse: "Anything else",
} as const
