export const fixturesCopy = {
  noaBerkovich: "Noa Berkovich",
  noab: "noab",
  noaExampleCom: "noa@example.com",
  text972542184409: "+972 54 218 4409",
  woman: "Woman",
  text19970418: "1997-04-18",
  mostlyFootballSometimesCatanUsuallyTheOneWithThe: "Mostly football, sometimes Catan. Usually the one with the lime kit bag.",
  florentinTelAviv: "Florentin, Tel Aviv",
  football: "Football",
  footballSoccer: "Football/Soccer",
  codingNight: "Coding night",
  codingHackNight: "Coding/Hack night",
  playground: "Playground",
  playgroundMeetup: "Playground meetup",
  asiaJerusalem: "Asia/Jerusalem",
  openToEveryone: "Open to everyone",
  everyoneWelcome: "Everyone welcome",
  split: "Split",
  ticketed: "Ticketed",
  pay: "Pay",
  happyToLearnTheRulesIsThereStillRoom: "Happy to learn the rules. Is there still room?",
  sundayMorningRunAlongTheBeach: "Sunday morning run along the beach",
  fiveASideRainedOff: "Five-a-side, rained off",
  thePitchFloodedWeWillTryAnotherDay: "The pitch flooded. We will try another day.",
  meetingPointGateBesideTheTennisCourtsLookFor: "Meeting point: gate beside the tennis courts. Look for the lime kit bag. Bring a dark shirt and a light one!",
  mayaAdler: "Maya Adler",
  iCanBringABallIfWeNeedAnother: "I can bring a ball if we need another one.",
  talRavid: "Tal Ravid",
  perfectSeeYouThereTenMinutesEarly: "Perfect. See you there, ten minutes early.",
  yonatanShalev: "Yonatan Shalev",
  standardCatanTonightNewPlayersWelcome: "Standard Catan tonight. New players welcome!",
  threePeopleWantToJoin: "Three people want to join",
  ariRoniAndOmriRequestedASpotInYour: "Ari, Roni and Omri requested a spot in your Tuesday game.",
  yourConnectIsComingUp: "Your Connect is coming up",
  fiveASideShortTwoPlayersBringADark: "Five-a-side, short two players. Bring a dark shirt and a light one.",
  mayaSentAMessage: "Maya sent a message",
} as const
