export const formatCopy = {
  today: "Today",
  tomorrow: "Tomorrow",
  free: "Free",
  payYourOwn: "Pay your own",
  separator: (value0: string | number, value1: string | number) => "" + String(value0) + " \u20aa" + String(value1) + "",
  split: "Split",
  ticketed: "Ticketed",
  fullJoinWaitlist: "Full \u00b7 join waitlist",
  ofSpotsLeft: (value0: string | number, value1: string | number) => "" + String(value0) + " of " + String(value1) + " spots left",
  online: "Online",
  placeTBD: "Place TBD",
  distanceUnavailable: "Distance unavailable",
  happeningNow: "Happening now",
  inM: (value0: string | number) => "In " + String(value0) + " m",
  inH: (value0: string | number) => "In " + String(value0) + " h",
  h: (value0: string | number) => "" + String(value0) + " h",
  m: (value0: string | number) => " " + String(value0) + " m",
  going: (value0: string | number) => "" + String(value0) + " going",
  km: (value0: string | number) => "" + String(value0) + " km",
} as const
