export const formatCopy = {
  today: "Today",
  tomorrow: "Tomorrow",
  free: "Free",
  payYourOwn: "Pay your own",
  formatCost: (costTypeLabel: string | number, costAmount: string | number) => "" + String(costTypeLabel) + " \u20aa" + String(costAmount) + "",
  split: "Split",
  ticketed: "Ticketed",
  fullJoinWaitlist: "Full \u00b7 join waitlist",
  remainingSpotsLabel: (availableSpots: string | number, capacity: string | number) => "" + String(availableSpots) + " of " + String(capacity) + " spots left",
  online: "Online",
  placeToBeDecided: "Place TBD",
  distanceUnavailable: "Distance unavailable",
  happeningNow: "Happening now",
  startsInMinutes: (minutes: string | number) => "In " + String(minutes) + " m",
  startsInHours: (hours: string | number) => "In " + String(hours) + " h",
  formatHours: (hours: string | number) => "" + String(hours) + " h",
  formatMinutes: (minutes: string | number) => " " + String(minutes) + " m",
  attendanceCountLabel: (attendeeCount: string | number) => "" + String(attendeeCount) + " going",
  formatDistanceKilometers: (distanceKilometers: string | number) => "" + String(distanceKilometers) + " km",
} as const
