export const storeCopy = {
  addYourBirthDateInYourProfileToJoin: "Add your birth date in your profile to join this age-restricted Connect.",
  yourAgeIsOutsideThisConnectSAgeRange: "Your age is outside this Connect's age range.",
  womenOnly: "Women only",
  woman: "Woman",
  thisConnectIsForWomenOnlyCheckYourProfile: "This Connect is for women only. Check your profile or choose another Connect.",
  chooseADefaultRadiusFrom1To100Km: "Choose a default radius from 1 to 100 km.",
  signInToEditYourProfile: "Sign in to edit your profile.",
  profileSaved: "Profile saved.",
  signInToSaveYourSpot: "Sign in to save your spot.",
  thisConnectIsNoLongerAvailable: "This Connect is no longer available.",
  thisConnectIsNoLongerAcceptingPeople: "This Connect is no longer accepting people.",
  unblockThisHostBeforeJoining: "Unblock this host before joining.",
  youAreAlreadyOnTheList: "You are already on the list.",
  youAreGoing: "You are going!",
  requestSent: "Request sent",
  addedToTheWaitlist: "Added to the waitlist",
  youAreInFindThisConnectInMyConnects: "You are in! Find this Connect in My Connects.",
  requestSentTheHostWillNeedToApproveYou: "Request sent. The host will need to approve you.",
  youAreOnTheWaitlistTheHostCanOffer: "You are on the waitlist. The host can offer you a spot.",
  signInAndOpenAnExistingConnect: "Sign in and open an existing Connect.",
  hostsMustCancelTheirConnectInsteadOfLeaving: "Hosts must cancel their Connect instead of leaving.",
  youHaveLeftThisConnect: "You have left this Connect.",
  signInToHostAConnect: "Sign in to host a Connect.",
  youCanOnlyPublishAsYourself: "You can only publish as yourself.",
  thisConnectHasAlreadyBeenPublished: "This Connect has already been published.",
  theHostMustBeIncludedInConfirmedAttendance: "The host must be included in confirmed attendance.",
  capacityCannotBeLowerThanConfirmedAttendance: "Capacity cannot be lower than confirmed attendance.",
  chooseAnEndTimeAfterTheStartTime: "Choose an end time after the start time.",
  privateLocationsRequireHostApproval: "Private locations require host approval.",
  yourConnectIsPublished: "Your Connect is published.",
  onlyTheHostCanEditThisConnect: "Only the host can edit this Connect.",
  thisConnectCanNoLongerBeEdited: "This Connect can no longer be edited.",
  capacityCannotBeLowerThanTheNumberOfConfirmed: "Capacity cannot be lower than the number of confirmed people.",
  connectUpdated: "Connect updated",
  changesSaved: "Changes saved.",
  onlyTheHostCanCancelThisConnect: "Only the host can cancel this Connect.",
  thisConnectIsAlreadyCancelled: "This Connect is already cancelled.",
  connectCancelled: "Connect cancelled",
  connectCancelled2: "Connect cancelled.",
  onlyTheHostCanManageRequests: "Only the host can manage requests.",
  thatRequestHasAlreadyBeenHandled: "That request has already been handled.",
  unblockThisMemberBeforeApprovingTheirRequest: "Unblock this member before approving their request.",
  thisConnectIsFullIncreaseCapacityOrFreeA: "This Connect is full. Increase capacity or free a spot first.",
  requestApproved: "Request approved",
  requestDeclined: "Request declined",
  isOnTheList: (name: string | number) => "" + String(name) + " is on the list.",
  requestDeclined2: "Request declined.",
  joinThisConnectBeforeSendingAMessage: "Join this Connect before sending a message.",
  thisChatIsReadOnlyBecauseTheConnectHas: "This chat is read-only because the Connect has ended or was cancelled.",
  writeAMessageBetween1And2000Characters: "Write a message between 1 and 2,000 characters.",
  messageSaved: "Message saved.",
  youCannotBlockThisProfile: "You cannot block this profile.",
  userBlockedSharedAttendanceAndPrivateLocationAccessHave: "User blocked. Shared attendance and private-location access have been removed.",
  signInAndProvideAReportReason: "Sign in and provide a report reason.",
  reportSaved: "Report saved.",
  onlyAttendeesCanRateACompletedConnectHostedBy: "Only attendees can rate a completed Connect hosted by someone else, from 1 to 5 stars.",
  yourRatingHasBeenSaved: "Your rating has been saved.",
} as const
