export const hostPageCopy = {
  yourSavedDraftCouldNotBeOpenedYouCan: "Your saved draft could not be opened. You can start again; the original draft has not been changed.",
  yourSavedDraftCouldNotBeOpenedKeepThis: "Your saved draft could not be opened. Keep this page open until you can save your changes.",
  aProfileMakesYouTheHost: "A profile makes you the host",
  createAProfile: "Create a profile",
  createAProfileToHostAndManageYourConnects: "Create a profile to host and manage your Connects.",
  thisConnectCouldNotBeFound: "This Connect could not be found",
  backToMyConnects: "Back to My Connects",
  theLinkMayBeOutOfDate: "The link may be out of date.",
  onlyTheHostCanEditThisConnect: "Only the host can edit this Connect",
  viewTheConnect: "View the Connect",
  signInWithTheProfileThatCreatedThisConnect: "Sign in with the profile that created this Connect.",
  thisConnectIsNoLongerEditable: "This Connect is no longer editable",
  viewHostManagement: "View host management",
  cancelledAndEndedConnectsKeepTheirOriginalDetails: "Cancelled and ended Connects keep their original details.",
  chooseAVenue: "Choose a venue",
  online: "Online",
  placeToBeDecided: "Place to be decided",
  firstOccurrence: " (first occurrence)",
  secondOccurrence: " (second occurrence)",
  chooseADateAndTime: "Choose a date and time",
  noLimit: "No limit",
  peopleIncludingYou: (value: string | number) => "" + String(value) + " people, including you",
  draftSaved: "Draft saved.",
  yourDraftCouldNotBeSavedKeepThisPage: "Your draft could not be saved. Keep this page open and try again.",
  savedDraftDiscarded: "Saved draft discarded.",
  yourDraftCouldNotBeDiscardedYourChangesHave: "Your draft could not be discarded. Your changes have been kept.",
  chooseAValidTimezoneBeforeUsingADateShortcut: "Choose a valid timezone before using a date shortcut.",
  thereIsLessThanAnHourLeftTodayPick: "There is less than an hour left today. Pick a time manually or choose tomorrow.",
  someDetailsNeedAttentionReviewTheHighlightedFieldsBefore: "Some details need attention. Review the highlighted fields before publishing.",
  theTimeOrMapPinIsNoLongerValid: "The time or map pin is no longer valid. Please review those steps.",
  theSavedConnectCouldNotBeFoundYourForm: "The saved Connect could not be found. Your form has been kept; reopen My Connects before trying again.",
  yourConnectWasSavedButItsOldDraftCould: "Your Connect was saved, but its old draft could not be removed.",
  category: "Category",
  theWords: "The words",
  editTheTitleAndDescriptionAbove: "Edit the title and description above",
  otherActivity: "Other activity",
  bringAlong: "Bring along",
  nothingSpecific: "Nothing specific",
  when: "When",
  happeningNow: "Happening now. ",
  venue: "Venue",
  publicArea: "Public area",
  meetingPoint: "Meeting point",
  meetAtTheConfirmedPin: "Meet at the confirmed pin",
  meetingDetails: "Meeting details",
  toBeDecided: "To be decided",
  spots: "Spots",
  whoCanSeeIt: "Who can see it",
  joining: "Joining",
  youApproveEachRequest: "You approve each request",
  instantJoining: "Instant joining",
  locationPrivacy: "Location privacy",
  joiningDetailsAreSharedWithConfirmedAttendees: "Joining details are shared with confirmed attendees",
  meetingDetailsHiddenUntilApproval: "Meeting details hidden until approval",
  meetingDetailsArePublic: "Meeting details are public",
  guestList: "Guest list",
  onlyYouCanSeeTheNamesEveryoneElseSees: "Only you can see the names; everyone else sees the count.",
  visibleToEveryoneWhoCanSeeThisConnect: "Visible to everyone who can see this Connect",
  skillLevel: "Skill level",
  ageRange: "Age range",
  cost: "Cost",
  editYourConnect: "Edit your Connect",
  hostAConnect: "Host a Connect",
  changesSaved: "Changes saved",
  published: "Published",
  stepOf8: (stepNumber: string | number) => "Step " + String(stepNumber) + " of 8",
  saveAndClose: "Save and close",
  hostingProgress: "Hosting progress",
  sentenceEndingWithSpace: ". ",
  yourDraftIsReadyToContinue: "Your draft is ready to continue. ",
  discardSavedDraft: "Discard saved draft",
  readyToConnect: "Ready to connect",
  step: (stepNumber: string | number, name: string | number) => "Step " + String(stepNumber) + " / " + String(name) + "",
  chooseYourSubcategories: "Choose your subcategories",
  checkmarkSymbol: "\u2713",
  theDetailsAreUpToDate: "The details are up to date.",
  linkOnly: "Link only",
  readyForYourInvitedCircle: "Ready for your invited circle.",
  itSOnTheBoard: "It's on the board.",
  yourConnectIsAvailableByLinkAndWillNot: "Your Connect is available by link and will not appear in Discover.",
  yourConnectIsPublished: "Your Connect is published.",
  youApproveEachRequestBeforeSomeoneJoins: "You approve each request before someone joins.",
  peopleCanJoinStraightAwayWhileThereIsSpace: "People can join straight away while there is space.",
  viewYourConnect: "View your Connect",
  inviteFriends: "Invite friends",
  manageYourConnect: "Manage your Connect",
  chooseACategory: "Choose a category",
  subcategoriesFor: "Subcategories for ",
  chooseAllThatFit: ", choose all that fit",
  selectedYouCanChooseMoreThanOne: " selected. You can choose more than one.",
  title: "Title",
  sayWhatYouArePlanningAndWhoYouWould: "Say what you are planning and who you would like to join.",
  giveYourConnectAClearTitle: "Give your Connect a clear title",
  descriptionOptional: "Description (optional)",
  whatShouldPeopleKnowBeforeJoining: "What should people know before joining?",
  whatToBringOptional: "What to bring (optional)",
  anythingPeopleShouldBring: "Anything people should bring",
  describeYourOtherActivity: "Describe your Other activity",
  tellPeopleWhatThisActivityIsThisDetailIs: "Tell people what this activity is. This detail is required when you choose Other.",
  whenAreYouConnect: "When are you connect?",
  happeningNow2: "Happening now",
  planForLater: "Plan for later",
  timezone: "Timezone",
  datesAndTimesUseThisTimezone: "Dates and times use this timezone.",
  europeLondon: "Europe/London",
  asiaJerusalem: "Asia/Jerusalem",
  utcTimeZone: "UTC",
  europeParis: "Europe/Paris",
  americaNewYork: "America/New_York",
  americaLosAngeles: "America/Los_Angeles",
  asiaKolkata: "Asia/Kolkata",
  australiaSydney: "Australia/Sydney",
  thisConnectHasAlreadyStartedChooseWhenItEnds: "This Connect has already started. Choose when it ends.",
  startsWhenYouPublishChooseAnEndTimeSo: "Starts when you publish. Choose an end time so people know when it wraps up.",
  startDate: "Start date",
  starts: "Starts",
  startTimeOccurrence: "Start time occurrence",
  firstOccurrence2: "First occurrence",
  secondOccurrence2: "Second occurrence",
  thisTimeHappensTwiceWhenTheClocksGoBack: "This time happens twice when the clocks go back. Which occurrence do you mean?",
  laterToday: "Later today",
  tomorrow: "Tomorrow",
  thisWeekend: "This weekend",
  endDate: "End date",
  ends: "Ends",
  endTimeOccurrence: "End time occurrence",
  whereWillItHappen: "Where will it happen?",
  aPlace: "A place",
  chooseAndConfirmAValidLocation: "Choose and confirm a valid location.",
  meetingPointAndInstructionsOptional: "Meeting point and instructions (optional)",
  whereShouldPeopleMeetYou: "Where should people meet you?",
  hideTheExactAddressUntilYouApproveSomeone: "Hide the exact address until you approve someone",
  approval: "approval",
  publicNeighbourhoodOrArea: "Public neighbourhood or area",
  shownInsteadOfYourExactAddressUseANeighbourhood: "Shown instead of your exact address. Use a neighbourhood, not a street address.",
  neighbourhoodOrArea: "Neighbourhood or area",
  pickSomewherePublicForAFirstMeeting: "Pick somewhere public for a first meeting.",
  aParkGateACafeACourtEntranceIf: "A park gate, a cafe, a court entrance. If you host at home, hide the exact address and approve each guest.",
  thisOneHappensOnline: "This one happens online",
  youWillDecideThePlaceLater: "You will decide the place later",
  addJoiningDetailsForConfirmedAttendeesOrShareThem: "Add joining details for confirmed attendees, or share them later in the group conversation.",
  yourConnectWillShowAsPlaceToBeDecided: "Your Connect will show as Place to be decided. Edit it once you know where to meet.",
  online2: "online",
  onlineJoiningDetailsOptional: "Online joining details (optional)",
  meetingPlansOptional: "Meeting plans (optional)",
  aMeetingLinkOrJoiningInstructions: "A meeting link or joining instructions",
  howYouWillChooseAPlaceToMeet: "How you will choose a place to meet",
  keepMeetingDetailsPrivate: "Keep meeting details private",
  capacity: "Capacity",
  people: (value: string | number) => "" + String(value) + " people",
  noCapacityLimit: "No capacity limit",
  privateDetailsRequireApproval: "Private meeting details require you to approve each request.",
  instantJoiningLockedByPrivacy: "Instant joining is unavailable while Keep meeting details private is on. Turn it off to let people join instantly.",
  instantJoiningAvailable: "Meeting details are not private. Choose Instantly to let people join without approval, or keep approving requests.",
  instantJoiningEnabled: "People can join instantly while there is space. Turning on Keep meeting details private will require approval again.",
  totalPeopleIncludingYou: "Total people, including you",
  quickCapacitySelectorZeroMeansNoLimit: "Quick capacity selector, zero means no limit",
  slideToZeroForNoLimitOrTypeAny: "Slide to zero for no limit, or type any larger capacity above.",
  everyone: "Everyone",
  notListedInDiscoverAnyoneWithTheLinkCan: "Not listed in Discover. Anyone with the link can open it; your joining rules still apply.",
  listedInDiscoverForPeopleBrowsingNearby: "Listed in Discover for people browsing nearby.",
  instantly: "Instantly",
  approveRequests: "Approve requests",
  keepTheGuestListPrivate: "Keep the guest list private",
  hideTheExactAddress: "Hide the exact address",
  approvalIsRequiredMeetingDetailsStayPrivateUntilSomeone: "Approval is required. Meeting details stay private until someone is confirmed.",
  joiningDetailsAreSharedWithConfirmedAttendees2: "Joining details are shared with confirmed attendees.",
  meetingDetailsAreVisibleToEveryoneWhoCanOpen: "Meeting details are visible to everyone who can open this Connect.",
  openToEveryoneUnlessTheActivityGenuinelyNeedsA: "Open to everyone unless the activity genuinely needs a baseline.",
  womenOnly: "Women only",
  onlySetThisWhereItMattersSuchAsAn: "Only set this where it matters, such as an adults-only bar crawl.",
  freeUnlessYouSayOtherwiseSplitCostDividesThe: "Free unless you say otherwise. Split cost divides the total between the people who attend.",
  split: "split",
  totalToSplitILS: "Total to split (ILS)",
  costPerPersonILS: "Cost per person (ILS)",
  text200: "200",
  edit: (value: string | number) => "Edit " + String(value) + "",
  edit2: "Edit",
  back: "Back",
  continue: "Continue ",
  forwardArrow: "\u2192",
  saving: "Saving...",
  saveChanges: "Save changes",
  publishThisConnect: "Publish this Connect",
  backToReview: "Back to review",
  feedCard: "Feed card",
  howItWillLookInTheFeed: "How it will look in the feed",
  yourNextGoodPlanStartsHere: "Your next good plan starts here",
  exactAddressHidden: (value: string | number) => "" + String(value) + " / Exact address hidden",
  yourNeighbourhood: "Your neighbourhood",
  chooseAPlaceToMeet: "Choose a place to meet",
  chooseAStartTime: "Choose a start time",
  approval2: "Approval",
  instantJoin: "Instant join",
  placeStartTimeAndSpotsAreWhatPeopleScan: "Place, start time and spots are what people scan first. Everything else they read after they have stopped.",
  onlyPeopleWithTheLinkCanFindThisConnect: "Only people with the link can find this Connect.",
  shareThisLinkWithThePeopleYouWouldLike: "Share this link with the people you would like to invite.",
  done: "Done",
} as const
