export const hostSchemaCopy = {
  category: "Category",
  whatKindOfConnectIsThis: "What kind of Connect is this?",
  categorySetsTheColourPeopleScanForInThe: "Category sets the colour people scan for in the feed and on the map.",
  subcategory: "Subcategory",
  narrowItDown: "Narrow it down",
  pickAsManyAsFitPeopleFilterOnThese: "Pick as many as fit. People filter on these, so the more accurate the better.",
  theWords: "The words",
  titleAndDescription: "Title and description",
  plainAndSpecificBeatsCleverPeopleDecideFromThe: "Plain and specific beats clever. People decide from the title alone.",
  when: "When",
  dateStartAndEnd: "Date, start and end",
  everyConnectHasAnEndTimeSoPeopleKnow: "Every Connect has an end time so people know what they are committing to.",
  where: "Where",
  locationAndMeetingPoint: "Location and meeting point",
  aPinGetsPeopleToThePlaceTheMeeting: "A pin gets people to the place. The meeting point gets them to you.",
  theRules: "The rules",
  spotsVisibilityAndJoining: "Spots, visibility and joining",
  startWithTheDefaultsThenMakeThisConnectWork: "Start with the defaults, then make this connect work for you.",
  details: "Details",
  skillAgeAndCost: "Skill, age and cost",
  allThreeDefaultToOpenSetThemOnlyWhere: "All three default to open. Set them only where they genuinely matter.",
  review: "Review",
  checkItOver: "Check it over",
  reviewYourConnectBeforePublishingYouCanEditAny: "Review your Connect before publishing. You can edit any section.",
  openToEveryone: "Open to everyone",
  beginner: "Beginner",
  intermediate: "Intermediate",
  advanced: "Advanced",
  everyoneWelcome: "Everyone welcome",
  over18: "Over 18",
  free: "Free",
  splitCost: "Split cost",
  payYourOwn: "Pay your own",
  ticketed: "Ticketed",
  everyone: "Everyone",
  linkOnly: "Link only",
  other: "Other",
  mustBeCharacters: (label: string | number, secondValue: string | number) => "" + String(label) + " must be " + String(secondValue) + " characters.",
  atMost: (maximum: string | number) => "at most " + String(maximum) + "",
  chooseAtLeastOneSubcategory: "Choose at least one subcategory.",
  chooseSubcategoriesFromTheSelectedCategory: "Choose subcategories from the selected category.",
  theTitle: "The title",
  theDescription: "The description",
  whatToBring: "What to bring",
  theOtherDescription: "The Other description",
  thePublicNeighbourhoodOrArea: "The public neighbourhood or area",
  meetingInstructions: "Meeting instructions",
  keepMeetingDetailsTo500CharactersOrFewer: "Keep meeting details to 500 characters or fewer.",
  chooseAVenueAndExplicitlyConfirmItsMapPin: "Choose a venue and explicitly confirm its map pin.",
  selectAValidLocationFromTheMapPicker: "Select a valid location from the map picker.",
  capacityMustBeAWholeNumberOfAtLeast: (value: string | number) => "Capacity must be a whole number of at least " + String(value) + ", including everyone already going.",
  privateLocationsRequireHostApproval: "Private locations require host approval.",
  chooseASkillLevel: "Choose a skill level.",
  womenOnly: "Women only",
  chooseAnAgeRange: "Choose an age range.",
  enterAnAmountAbove0AndUpTo1: "Enter an amount above 0 and up to 1,000,000, with at most two decimal places.",
  chooseAValidTimezone: "Choose a valid timezone.",
  aScheduledConnectMustStartInTheFutureChoose: "A scheduled Connect must start in the future. Choose a later time or Happening now.",
  theEndMustBeAfterTheStartUseA: "The end must be after the start. Use a later end date for an overnight Connect.",
  theEndMustStillBeInTheFuture: "The end must still be in the future.",
  online: "Online",
  placeToBeDecided: "Place to be decided",
  hostApprovalIsRequiredOnlyYouAndConfirmedAttendees: "Host approval is required. Only you and confirmed attendees can see the exact address and meeting instructions; everyone else sees the area.",
  hostApprovalIsRequiredOnlyYouAndConfirmedAttendees2: "Host approval is required. Only you and confirmed attendees can see the meeting details or online joining link.",
  youApproveEachRequestJoiningDetailsAreSharedWith: "You approve each request. Joining details are shared with confirmed attendees.",
  peopleCanJoinInstantlyWhileThereIsSpaceJoining: "People can join instantly while there is space. Joining details are shared after they join.",
  everyRequestWaitsForYourApprovalYouChooseWho: "Every request waits for your approval. You choose who gets a spot; the public meeting details are visible to everyone.",
  anyoneEligibleWhoCanSeeThisConnectCanJoin: "Anyone eligible who can see this Connect can join instantly while there is space. When it is full, people can join the waitlist.",
  everyonePaysTheirOwnWay: "Everyone pays their own way",
  iLS: (costAmount: string | number, secondValue: string | number) => "" + String(costAmount) + " ILS " + String(secondValue) + "",
  totalSplitBetweenEveryone: "total, split between everyone",
  perPerson: "per person",
  amountToBeSet: "Amount to be set",
} as const
