export const managePageCopy = {
  going: "going",
  going2: "Going",
  pending: "Pending",
  waitlist: "Waitlist",
  signInToManageYourConnect: "Sign in to manage your Connect",
  createAProfile: "Create a profile",
  onlyTheHostCanManageThisConnect: "Only the host can manage this Connect.",
  thisConnectCouldNotBeFound: "This Connect could not be found",
  backToMyConnects: "Back to My Connects",
  theLinkMayBeOutOfDate: "The link may be out of date.",
  thisIsTheHostSSpace: "This is the host's space",
  viewTheConnect: "View the Connect",
  onlyTheHostCanSeeRequestsEditDetailsOr: "Only the host can see requests, edit details or manage the guest list.",
  backArrow: "\u2190",
  myConnects: " My Connects",
  youAreTheHost: "You are the host",
  viewPublicPage: "View public page",
  cancelled: "Cancelled",
  thisConnectIsNoLongerInDiscoverAndIs: "This Connect is no longer in Discover and is not accepting new people.",
  reason: "Reason: ",
  thisConnectHasEndedItsGuestListIsA: "This Connect has ended. Its guest list is a record of who joined; host controls are now read-only.",
  commaSeparatorWithSpace: ", ",
  textSeparator: " - ",
  textSeparator2: " (",
  textSeparator3: ")",
  textSeparator4: " / ",
  going3: " going",
  noCapacityLimit: " / No capacity limit",
  totalSpots: (capacity: string | number) => " / " + String(capacity) + " total spots",
  goingIncludingYou: "Going, including you",
  requestsWaiting: "Requests waiting",
  onTheWaitlist: "On the waitlist",
  allSpotsAreFilledIncreaseCapacityIn: "All spots are filled. Increase capacity in ",
  editTheDetails: "Edit the details",
  orRemoveAConfirmedGuestBeforeApprovingSomeoneElse: " or remove a confirmed guest before approving someone else. Existing requests stay here until you decide.",
  guestLists: "Guest lists",
  previouslyGoing: "Previously going",
  thePeopleMakingItHappen: "The people making it happen",
  nextInLine: "Next in line",
  whenASpotOpensUpApproveSomeoneToMove: "When a spot opens up, approve someone to move them to the confirmed list.",
  nothingWaitingOnYou: "Nothing waiting on you",
  noOneOnTheWaitlist: "No one on the waitlist",
  noConfirmedAttendees: "No confirmed attendees",
  thisConnectIsClosedSoNewRequestsAreNot: "This Connect is closed, so new requests are not accepted.",
  newRequestsLandHereYouCanApproveOrDecline: "New requests land here. You can approve or decline each one.",
  ifALimitedCapacityConnectFillsUpNewPeople: "If a limited-capacity Connect fills up, new people can join its waitlist.",
  theConfirmedGuestListWillAppearHere: "The confirmed guest list will appear here.",
  hostYou: "Host / you",
  confirmed: "Confirmed",
  wouldLikeToJoin: "Would like to join",
  waitingForASpot: "Waiting for a spot",
  remove: (name: string | number) => "Remove " + String(name) + "",
  remove2: "Remove",
  decline: (name: string | number) => "Decline " + String(name) + "",
  decline2: "Decline",
  approve: (name: string | number) => "Approve " + String(name) + "",
  offerSpot: "Offer spot",
  approve2: "Approve",
  onlyYouCanSeeTheNamesEveryoneElseSees: "Only you can see the names; everyone else sees the count.",
  theConfirmedGuestListIsPublicPendingRequestsAnd: "The confirmed guest list is public. Pending requests and the waitlist are host-only.",
  hostControls: "Host controls",
  detailsAreReadOnlyFor: "Details are read-only for ",
  connects: " Connects.",
  viewGroupConversation: "View group conversation",
  messageEveryone: "Message everyone",
  shareLink: "Share link",
  capacity: "Capacity",
  noLimit: "No limit",
  full: "Full",
  spotsLeft: (value: string | number) => "" + String(value) + " spots left",
  outOf: (capacity: string | number) => " out of " + String(capacity) + "",
  includingYou: ", including you.",
  ofSpotsFilled: (attendeeCount: string | number, capacity: string | number) => "" + String(attendeeCount) + " of " + String(capacity) + " spots filled",
  changeCapacity: "Change capacity",
  whoCanJoin: "Who can join",
  instantly: "Instantly",
  approveRequests: "Approve requests",
  approval: "approval",
  hideTheExactAddress: "Hide the exact address",
  keepMeetingDetailsPrivate: "Keep meeting details private",
  onlyConfirmedAttendeesCanSeeTheMeetingDetailsTurning: "Only confirmed attendees can see the meeting details. Turning privacy on also requires approval for new joiners.",
  online: "online",
  joiningDetailsAreAvailableToConfirmedAttendees: "Joining details are available to confirmed attendees.",
  meetingDetailsAreVisibleToEveryoneWhoCanOpen: "Meeting details are visible to everyone who can open this Connect.",
  privateGuestList: "Private guest list",
  whoCanSeeIt: "Who can see it",
  everyone: "Everyone",
  linkOnly: "Link only",
  hiddenFromDiscoverAnyoneWithTheLinkCanOpen: "Hidden from Discover. Anyone with the link can open it.",
  listedInDiscoverWhileItIsActive: "Listed in Discover while it is active.",
  cancelThisConnect: "Cancel this Connect",
  thisConnectIsCancelled: "This Connect is cancelled.",
  thisConnectHasAlreadyEnded: "This Connect has already ended.",
  itWillNoLongerAppearInDiscoverOrAccept: "It will no longer appear in Discover or accept new people. Cancellation cannot be undone.",
  alreadyEnded: "Already ended",
  shareYourConnect: "Share your Connect",
  done: "Done",
  remove3: (name: string | number) => "Remove " + String(name) + "?",
  theyWillLoseTheirConfirmedSpotAndAccessTo: "They will lose their confirmed spot and access to the group conversation and private meeting details.",
  keepOnTheList: "Keep on the list",
  removeGuest: "Remove guest",
  keepTheReasonTo500CharactersOrFewer: "Keep the reason to 500 characters or fewer.",
  enterANeighbourhoodOrArea: "Enter a neighbourhood or area.",
  keepTheAreaTo100CharactersOrFewer: "Keep the area to 100 characters or fewer.",
  chooseTheNeighbourhoodPeopleCanSeeBeforeYouApprove: "Choose the neighbourhood people can see before you approve their request.",
  publicNeighbourhoodOrArea: "Public neighbourhood or area",
  useANeighbourhoodNotAStreetAddress: "Use a neighbourhood, not a street address.",
  keepCurrentVisibility: "Keep current visibility",
  hideExactAddress: "Hide exact address",
  cancelThisConnect2: "Cancel this Connect?",
  guestIs: "guest is",
  guestsAre: "guests are",
  countingOnThis: " counting on this.",
  thisConnectWillNoLongerAppearInDiscoverOr: " This Connect will no longer appear in Discover or accept new people. You cannot undo cancellation.",
  reasonOptional: "Reason (optional)",
  addAReasonPeopleCanReadOnTheConnect: "Add a reason people can read on the Connect.",
  whyAreYouCancelling: "Why are you cancelling?",
  keepThisConnect: "Keep this Connect",
  cancelling: "Cancelling...",
  yesCancelIt: "Yes, cancel it",
} as const
