export const shellCopy = {
  welcome: "Welcome",
  signUp: "Sign up",
  discover: "Discover",
  detail: "Detail",
  host: "Host",
  categories: "Categories",
  myConnects: "My Connects",
  manage: "Manage",
  chat: "Chat",
  profile: "Profile",
  alerts: "Alerts",
  kit: "Kit",
  skipToContent: "Skip to content",
  previewNavigation: "Preview navigation",
  altShiftO: "Alt+Shift+O",
  preview: "Preview",
  allPreviewScreens: "All preview screens",
  layout: "Layout ",
  split: "Split",
  board: "Board",
  card: "Card ",
  row: "Row",
  tile: "Tile",
  palette: "Palette ",
  ink: "Ink",
  riso: "Riso",
  switchToTheme: (value: string | number) => "Switch to " + String(value) + " theme",
  light: "Light",
  dark: "Dark",
  connect: "Connect",
  findYourPeople: "Find Your People",
  search: "Search",
  footballBoardGamesFlorentin: "Football, board games, Florentin...",
  clearSearch: "Clear search",
  closeSymbol: "\u2715",
  mainNavigation: "Main navigation",
  chats: "Chats",
  logIn: "Log in",
  notifications: (value: string | number) => "Notifications" + String(value) + "",
  hostAConnect: "Host a Connect",
  yourProfile: "Your profile",
  dismissNotification: "Dismiss notification",
  yourNextPlanStartsHere: "Your next plan starts here",
  aNameToExpectAtTheGate: "A name to expect at the gate.",
  youCanBrowseAnyConnectAsAGuestSign: "You can browse any Connect as a guest. Sign up to join, host, or send a message.",
  iHaveAnAccount: "I have an account",
  light2: "light",
  dark2: "dark",
  unread: (alertCount: string | number) => ", " + String(alertCount) + " unread",
} as const
