export const welcomePageCopy = {
  enterAValidEmailAddress: "Enter a valid email address.",
  useAtLeast8Characters: "Use at least 8 characters.",
  weCouldnTSignYouInPleaseTryAgain: "We couldn't sign you in. Please try again later.",
  easyPlansWithTheFriendsYouHaveNotMet: "Easy plans with the friends you have not met yet.",
  itSTheGroupChatYouWereNeverAdded: "It's the group chat you were never added to. Someone's got a court booked and no fourth for doubles. A seat going spare at a Catan table. A run group leaves at 6:45, no roll call. Grab one nearby, or start your own and wait.",
  browseAsGuest: "Browse as guest",
  signUp: "Sign up",
  noAccountNeededToLookAround: "No account needed to look around.",
  findOneNearby: "Find one nearby",
  sortedByDistanceAndStartTimeSoTheClosest: "Sorted by distance and start time, so the closest thing happening soonest lands at the top.",
  joinAConnect: "Join a Connect",
  oneButtonAndYouAreExpectedSomewhereOnTuesday: "One button and you are expected somewhere on Tuesday. That is the whole commitment.",
  hostAConnect: "Host a Connect",
  pickACategorySetATimeAndAPublic: "Pick a category, set a time and a public meeting point, and let neighbours fill the spots.",
  meetingStrangersSensibly: "Meeting strangers, sensibly",
  memberProfiles: "Member profiles",
  getToKnowThePeopleYouReMeeting: " \u2014 get to know the people you're meeting.",
  reliabilityScore: "Reliability score",
  attendanceRateIsPublic: " \u2014 attendance rate is public.",
  publicMeetingPoints: "Public meeting points",
  theDefaultWhenYouHost: " \u2014 the default when you host.",
  reportAndBlock: "Report and block",
  onEveryProfileAndConnect: " \u2014 on every profile and Connect.",
  text2Min: "2 min",
  toHostAConnect: "to host a Connect",
  openByDefault: "Open by default",
  anyoneNearbyCanJoin: "anyone nearby can join",
  guestsCanBrowseAndOpenAnyConnectYouLl: "Guests can browse and open any Connect. You'll need an account to join, host, or send a message.",
  communityNoticeBoardAndLogin: "Community notice board and login",
  soccerPhoto: "soccer photo",
  circleSymbol: "\u25cf",
  football: " Football",
  fiveASideShortTwoPlayers: "Five-a-side, short two players",
  parkHaYarkonTonight1930: "Park HaYarkon \u00b7 tonight 19:30",
  peopleAtABar: "people at a bar",
  diamondSymbol: "\u25c6",
  barCrawl: " Bar crawl",
  thursdayFourStopsRothschild: "Thursday, four stops, Rothschild",
  boardGameNightPhoto: "board game night photo",
  squareSymbol: "\u25a0",
  boardGames: " Board games",
  catanTableLookingForAFourth: "Catan table looking for a fourth",
  florentinTonight20001Seat: "Florentin \u00b7 tonight 20:00 \u00b7 1 seat",
  consoleGamingPhoto: "console gaming photo",
  console: " Console",
  marioKartOnTheCouch4Controllers: "Mario Kart on the couch, 4 controllers",
  basketballPhoto: "basketball photo",
  basketball: " Basketball",
  text3On3UntilItGetsDark: "3-on-3 until it gets dark",
  computerGamingPhotoLabel: "PC gaming photo",
  personalComputerLabel: " PC",
  lANNightBringYourOwnRig: "LAN night, bring your own rig",
  yourNextPlanIsCloserThanYouThink: "Your next plan is closer than you think.",
  findAConnectNearbyAndMakeItHappen: "Find a Connect nearby and make it happen.",
  welcomeBack: "Welcome back",
  somebodyNearbyIsTwoPlayersShortRightNow: "Somebody nearby is two players short right now.",
  email: "Email",
  youExampleCom: "you@example.com",
  password: "Password",
  forgotPassword: "Forgot password?",
  atLeast8Characters: "At least 8 characters",
  logIn: "Log in",
  or: "or",
  google: "Google",
  g: "G",
  google2: " Google",
  apple: "Apple",
  newHere: "New here? ",
  resetYourPassword: "Reset your password",
  enterTheEmailAddressAssociatedWithYourAccount: "Enter the email address associated with your account.",
  passwordRecoveryIsUnavailableRightNowPleaseTryAgain: "Password recovery is unavailable right now. Please try again later.",
  emailAddress: "Email address",
  resetPassword: "Reset password",
  continueWith: (provider: string | number) => "Continue with " + String(provider) + "",
  signInIsCurrentlyUnavailablePleaseTryAgainLater: " sign-in is currently unavailable. Please try again later.",
  close: "Close",
} as const
