export const alertsPageCopy = {
  reviewRequests: "Review requests",
  openChat: "Open chat",
  viewRequest: "View request",
  openConnect: "Open Connect",
  separator: "\u2715",
  separator2: "\u25d4",
  separator3: "\u2713",
  unread: "Unread",
  groupMessagesAreOnlyVisibleToConfirmedAttendees: "Group messages are only visible to confirmed attendees.",
  separator4: "\u00b7",
  connectNoLongerAvailable: "Connect no longer available",
  markAsRead: (value0: string | number) => "Mark \"" + String(value0) + "\" as read",
  markAsRead2: "Mark as read",
  read: "Read",
  notifications: "Notifications",
  markAllAsRead: "Mark all as read",
  notificationFilter: "Notification filter",
  all: "All",
  allNotifications: "All notifications",
  unreadNotifications: "Unread notifications",
  youReAllCaughtUp: "You're all caught up",
  nothingToReportYet: "Nothing to report yet",
  browseConnects: "Browse Connects",
  youHaveNoUnreadNotificationsYourReadNotificationsAre: "You have no unread notifications. Your read notifications are still in All.",
  updatesAboutYourConnectsWillAppearHere: "Updates about your Connects will appear here.",
  notificationPreferences: "Notification preferences",
  chooseTheUpdatesThatMatterToYou: "Choose the updates that matter to you.",
  emailUpdates: "Email updates",
  emailVisibilityIsManagedInYourProfile: "Email visibility is managed in your profile.",
  connectReminders: "Connect reminders",
  keepTrackOfUpcomingPlans: "Keep track of upcoming plans.",
  groupChatUpdates: "Group chat updates",
  updatesAboutMessagesInConnectsYouHaveJoined: "Updates about messages in Connects you have joined.",
  preferencesSaved: "Preferences saved.",
  all2: "all",
  unread2: "unread",
} as const
