export const chatPageCopy = {
  writeAMessageBeforeSending: "Write a message before sending.",
  use2000CharactersOrFewer: "Use 2,000 characters or fewer.",
  messageTheGroup: "Message the group",
  send: "Send",
  you: "You",
  separator: "\u00b7",
  pinned: "Pinned",
  groupChat: (value0: string | number) => "" + String(value0) + " group chat",
  separator2: "\u2013",
  going: " going",
  openConnect: "Open Connect",
  yourRequestIsAwaitingApproval: "Your request is awaiting approval",
  youAreOnTheWaitlist: "You are on the waitlist",
  joinThisConnectToOpenItsChat: "Join this Connect to open its chat",
  viewConnect: "View Connect",
  onlyConfirmedAttendeesCanReadAndSendGroupMessages: "Only confirmed attendees can read and send group messages.",
  groupMessagesUnlockWhenYouGetAConfirmedSpot: "Group messages unlock when you get a confirmed spot.",
  joinThisConnectToTakePartInTheGroup: "Join this Connect to take part in the group conversation.",
  separator3: "\u2316",
  pinnedOnlineDetails: "Pinned online details",
  meetingPlaceToBeDecided: "Meeting place to be decided",
  pinnedMeetingPoint: "Pinned meeting point",
  theHostHasNotAddedMeetingDetailsYet: "The host has not added meeting details yet.",
  cancelled: "Cancelled",
  ended: "Ended",
  chatHistoryIsReadOnlyNoNewMessagesCan: "Chat history is read-only. No new messages can be sent.",
  groupMessages: "Group messages",
  noMessagesYet: "No messages yet",
  thereAreNoSavedMessagesForThisConnect: "There are no saved messages for this Connect.",
  sayHelloAskAQuestionOrCoordinateWhatTo: "Say hello, ask a question, or coordinate what to bring.",
  aPlaceForYourGroupToTalk: "A place for your group to talk",
  createAProfile: "Create a profile",
  joinAConnectToStartAConversationWithThe: "Join a Connect to start a conversation with the group.",
  yourThreads: "Your threads",
  connectGroupChats: "Connect group chats",
  approvalPendingChatLocked: "Approval pending - chat locked",
  waitlistedChatLocked: "Waitlisted - chat locked",
  readOnlyChatHistory: "Read-only chat history",
  noMessagesYetSayHello: "No messages yet. Say hello!",
  joinAConnectAndItsGroupWillAppearHere: "Join a Connect and its group will appear here.",
  browseConnects: "Browse Connects",
  thisConnectWasNotFound: "This Connect was not found",
  yourNextConversationStartsNearby: "Your next conversation starts nearby",
  theLinkMayBeOutOfDateChooseA: "The link may be out of date. Choose a thread or find another Connect.",
  joinAGroupToSayHelloAndCoordinateYour: "Join a group to say hello and coordinate your plans.",
  enGB: "en-GB",
  pending: "pending",
  waitlist: "waitlist",
} as const
