export const kitPageCopy = {
  enterANameWithAtLeastTwoCharacters: "Enter a name with at least two characters.",
  use50CharactersOrFewer: "Use 50 characters or fewer.",
  enterAValidEmailAddress: "Enter a valid email address.",
  notAnEmail: "not-an-email",
  name: "Name",
  required: "Required",
  yourName: "Your name",
  focusedField: "Focused field",
  readOnly: "Read-only",
  readOnlyField: "Read-only field",
  emailAddress: "Email address",
  disabledField: "Disabled field",
  validate: "Validate",
  looksGood: "Looks good.",
  noConnectsAvailable: "No Connects available",
  findYourNextPlanOnDiscover: "Find your next plan on Discover.",
  browseConnects: "Browse Connects",
  openCapacity: " - open capacity",
  left: (available: string | number, secondValue: string | number) => " \u00b7 " + String(available) + " " + String(secondValue) + " left",
  connectCardAvatarStackFormInputs: "Connect card, avatar stack, form inputs",
  commaSeparatorWithSpace: ", ",
  openCapacity2: "Open capacity",
  spotsLeft: (available: string | number) => "" + String(available) + " spots left",
  joinPanel: "Join panel",
  ends: "Ends ",
  middleDotSeparator: "\u00b7",
  confirmedSpots: "Confirmed spots",
  openConnect: "Open Connect",
  buttonPressed: (name: string | number) => "" + String(name) + " button pressed.",
  componentSheet: "Component sheet",
  theColoursTypographyAndComponentsThatBringConnectTogether: "The colours, typography, and components that bring Connect together.",
  buttons: "Buttons",
  primary: "Primary",
  action: "Action",
  secondary: "Secondary",
  quiet: "Quiet",
  disabled: "Disabled",
  loading: "Loading",
  categoryPillsAndMapPins: "Category pills and map pins",
  mapPin: (name: string | number) => "" + String(name) + " map pin",
  clusterOf7Connects: "Cluster of 7 Connects",
  text7: "7",
  textSeparator: " / ",
  typography: "Typography",
  goodPlansStartNearby: "Good plans start nearby.",
  aLittleMoreTogether: "A little more together.",
  fiveASideShortTwoPlayers: "Five-a-side, short two players",
  findYourPeoplePickAPublicSpotAndMake: "Find your people, pick a public spot, and make something happen. Archivo keeps the details clear at every size.",
  today1930: "Today, 19:30 ",
  parkHaYarkon: " Park HaYarkon",
  captionAndSupportingInformation: "Caption and supporting information",
  badgesAndToggles: "Badges and toggles",
  published: "Published",
  text3RequestsWaiting: "3 requests waiting",
  going: "Going",
  approvalPending: "Approval pending",
  waitlisted: "Waitlisted",
  cancelled: "Cancelled",
  free: "Free",
  split: "Split ",
  textSeparator2: "\u20aa",
  text20: "20",
  ticketed: "Ticketed ",
  text50: "50",
  payYourOwn: "Pay your own",
  onByDefault: "On by default",
  optionalSetting: "Optional setting",
  disabledSwitch: "Disabled switch",
  topNavigation: "Top navigation",
  connectNavigation: "Connect navigation",
  connect: "Connect",
  discover: "Discover",
  myConnects: "My Connects",
  chats: "Chats",
  hostAConnect: "Host a Connect",
  going2: (attendeeCount: string | number, secondValue: string | number) => "" + String(attendeeCount) + " going" + String(secondValue) + "",
} as const
