export const myConnectsPageCopy = {
  hosting: "Hosting",
  joined: "Joined",
  invites: "Invites",
  past: "Past",
  loaded: "Loaded",
  loading: "Loading",
  empty: "Empty",
  error: "Error",
  chooseARatingFrom1To5Stars: "Choose a rating from 1 to 5 stars.",
  chooseAnAttendanceOptionOrLeaveItUnanswered: "Choose an attendance option or leave it unanswered.",
  onlyConfirmedAttendeesCanRateACompletedConnectHosted: "Only confirmed attendees can rate a completed Connect hosted by someone else.",
  howWas: "How was ",
  separator: "?",
  host: "host",
  rateTheHost: "Rate the host",
  separator2: "\u2605",
  everyoneShowedUp: "Everyone showed up? ",
  optional: "(optional)",
  yesEveryone: "Yes, everyone",
  someoneWasANoShow: "Someone was a no-show",
  updateRating: "Update rating",
  saveRating: "Save rating",
  feedbackSaved: "Feedback saved.",
  cancelled: "Cancelled",
  ended: "Ended",
  requestClosed: "Request closed",
  published: "Published",
  approvalPending: "Approval pending",
  waitlist: (value0: string | number) => "Waitlist #" + String(value0) + "",
  going: "Going",
  linkOnly: "Link only",
  separator3: ", ",
  separator4: "\u00b7",
  going2: " going",
  yourPlaceIsNotConfirmedYetTheHostNeeds: "Your place is not confirmed yet. The host needs to approve your request.",
  youAreWaitingForASpotBeingOnThe: "You are waiting for a spot. Being on the waitlist does not confirm attendance.",
  reviewRequests: "Review requests",
  manageConnect: "Manage Connect",
  editConnect: "Edit Connect",
  addToCalendar: "Add to calendar",
  cancel: "Cancel",
  openInviteLink: "Open invite link",
  openChat: "Open chat",
  leaveConnect: "Leave Connect",
  viewInvitation: "View invitation",
  viewRequest: "View request",
  leaveWaitlist: "Leave waitlist",
  withdrawRequest: "Withdraw request",
  yourRating5Edit: (value0: string | number) => "Your rating: " + String(value0) + "/5 - edit",
  viewConnect: "View Connect",
  viewChatHistory: "View chat history",
  youHavenTHostedOneYet: "You haven't hosted one yet",
  youHavenTJoinedAnythingYet: "You haven't joined anything yet",
  noInvitesRightNow: "No invites right now",
  nothingInYourHistoryYet: "Nothing in your history yet",
  hostAConnect: "Host a Connect",
  browseConnects: "Browse Connects",
  browseNearby: "Browse nearby",
  pickATimeAndAPlaceThenBringPeople: "Pick a time and a place, then bring people together.",
  pendingRequestsAndWaitlistedConnectsAppearHereOpenA: "Pending requests and waitlisted Connects appear here. Open a shared invitation link to see its details.",
  completedAndCancelledConnectsYouTookPartInWill: "Completed and cancelled Connects you took part in will appear here.",
  browseWhatIsOnNearbyOrPostTheThing: "Browse what is on nearby, or post the thing you were hoping someone else would.",
  yourConnectsStartHere: "Your Connects start here",
  createAProfile: "Create a profile",
  createAProfileToHostJoinAndKeepTrack: "Create a profile to host, join, and keep track of your Connects.",
  myConnects: "My Connects",
  changeDisplayState: "Change display state",
  state: "State: ",
  showMyConnects: "Show my Connects",
  connects: (value0: string | number) => "" + String(value0) + " Connects",
  loadingConnects: "Loading Connects",
  weCouldnTLoadYourConnects: "We couldn't load your Connects",
  tryAgainToLoadYourConnects: "Try again to load your Connects.",
  tryAgain: "Try again",
  withdrawYourRequest: "Withdraw your request?",
  leaveTheWaitlist: "Leave the waitlist?",
  leaveThisConnect: "Leave this Connect?",
  yourPlaceOrRequestWillBeRemovedYouCan: "Your place or request will be removed. You can join again while the Connect is open, but your previous spot is not reserved.",
  keepMyPlace: "Keep my place",
  confirmLeave: "Confirm leave",
  separator5: (value0: string | number, value1: string | number) => "" + String(value0) + " " + String(value1) + "",
  star: "star",
  stars: "stars",
  waiting: (value0: string | number, value1: string | number) => "" + String(value0) + " " + String(value1) + " waiting",
  spots: (value0: string | number) => " / " + String(value0) + " spots",
  pending: "pending",
  waitlist2: "waitlist",
} as const
