export const detailPageCopy = {
  pleaseDescribeTheProblemInAtLeast5Characters: "Please describe the problem in at least 5 characters.",
  keepYourNoteUnder500Characters: "Keep your note under 500 characters.",
  thisConnectIsNotAvailable: "This Connect is not available.",
  backToDiscover: "Back to Discover",
  itMayHaveBeenRemovedOrYouMayHave: "It may have been removed, or you may have blocked its host.",
  manageYourConnect: "Manage your Connect",
  thisConnectWasCancelled: "This Connect was cancelled",
  thisConnectHasEnded: "This Connect has ended",
  youAreGoing: "You are going \u2713",
  withdrawRequest: "Withdraw request",
  leaveWaitlist: "Leave waitlist",
  checkYourProfileToJoin: "Check your profile to join",
  joinWaitlist: "Join waitlist",
  requestToJoin: "Request to join",
  joinThisConnect: "Join this Connect",
  connectLinkCopied: "Connect link copied.",
  separator: "\u2190",
  backToDiscover2: " Back to Discover",
  roster: "Roster: ",
  hidden: "Hidden",
  public: "Public",
  cancelled: "Cancelled",
  ended: "Ended",
  full: "Full",
  requestPending: "Request pending",
  open: "Open",
  cancelledByTheHost: "Cancelled by the host",
  calledItOff: (value0: string | number) => "" + String(value0) + " called it off.",
  thisConnectHasEndedItRemainsInParticipantsHistory: "This Connect has ended. It remains in participants' history.",
  coverPhoto: (value0: string | number) => "cover photo \u2014 " + String(value0) + "",
  separator2: ", ",
  separator3: " \u2013 ",
  separator4: " \u00b7 ",
  approx: "(approx.)",
  hostApproves: "Host approves",
  openToEveryone: "Open to everyone",
  aboutThisActivity: "About this activity",
  whatToBring: "What to bring",
  justYourselfCheckTheGroupChatForAnyUpdates: "Just yourself. Check the group chat for any updates.",
  cost: "Cost",
  freeNothingToPayNothingToSortOutAfterwards: "Free. Nothing to pay, nothing to sort out afterwards.",
  everyonePaysTheirOwnWayNoKittyNoSplitting: "Everyone pays their own way. No kitty, no splitting at the end of the night.",
  totalSplitBetweenWhoeverTurnsUpCurrentlyAboutEach: (value0: string | number, value1: string | number) => "\u20aa" + String(value0) + " total, split between whoever turns up. Currently about \u20aa" + String(value1) + " each. Settle up with the host afterwards.",
  ticketedAtPerPersonPaidAtTheVenue: (value0: string | number) => "Ticketed at \u20aa" + String(value0) + " per person, paid at the venue.",
  meetOnline: "Meet online",
  meetingPlaceToBeDecided: "Meeting place to be decided",
  approximateArea: (value0: string | number) => "" + String(value0) + " \u00b7 approximate area",
  meetingDetailsAreSharedOnlyAfterTheHostApproves: "Meeting details are shared only after the host approves you. Public location distances are approximate.",
  timesAreShownIn: "Times are shown in ",
  separator5: ".",
  whoSComing: "Who's coming",
  peopleAreComing: " people are coming",
  keepsThisListPrivateOnlyTheHostCanSee: " keeps this list private. Only the host can see who has joined.",
  host: "Host",
  going: "Going",
  reportThisConnect: "Report this Connect",
  blockTheHost: "Block the host",
  ends: "Ends ",
  ofSpotsFilled: (value0: string | number, value1: string | number) => "" + String(value0) + " of " + String(value1) + " spots filled",
  requestSent: "Request sent",
  approvesEachRequestYouCanWithdrawWhileYouWait: " approves each request. You can withdraw while you wait.",
  youAreOnTheWaitlistTheHostCanOffer: "You are on the waitlist. The host can offer you a spot when one opens.",
  youAreTheHostManageAttendanceEditOrCancel: "You are the host. Manage attendance, edit, or cancel this Connect.",
  theHostCanSeeYouAreComingYouCan: "The host can see you are coming. You can leave from here.",
  theHostApprovesEachRequestBeforeTheExactPrivate: "The host approves each request before the exact private address is shared.",
  joiningIsInstantYouCanLeaveIfYourPlans: "Joining is instant. You can leave if your plans change.",
  groupChat: "Group chat",
  inviteFriends: "Invite friends",
  shareLink: "Share link",
  separator6: "\u2713",
  verified: " Verified",
  hostingSince2023: "Hosting since 2023 \u00b7 ",
  separator7: "\u2605",
  hostRating: "host rating",
  hosted: "hosted",
  separator8: "%",
  showUp: "show up",
  saveYourSpot: "Save your spot",
  signUpToLetTheHostKnowWhoTo: "Sign up to let the host know who to expect. You'll return to this Connect after signup.",
  signUpAndJoin: "Sign up and join",
  aShortIntroductionHelps: "A short introduction helps ",
  putANameToTheRequest: " put a name to the request.",
  aNoteToTheHostOptional: "A note to the host (optional)",
  happyToBringABall: "Happy to bring a ball!",
  sendRequest: "Send request",
  withdrawYourRequest: "Withdraw your request?",
  leaveTheWaitlist: "Leave the waitlist?",
  leaveThisConnect: "Leave this Connect?",
  yourSpotOrRequestWillBeRemovedYouCan: "Your spot or request will be removed. You can rejoin while the Connect still has space and is accepting people.",
  yesLeave: "Yes, leave",
  stayOnTheList: "Stay on the list",
  whatHappened: "What happened?",
  saveReport: "Save report",
  block: (value0: string | number) => "Block " + String(value0) + "?",
  youWonTSeeTheirConnectsAndYourAttendance: "You won't see their Connects, and your attendance and access to their private locations will be removed. Addresses already seen cannot be recalled.",
  blockHost: "Block host",
  keepConnected: "Keep connected",
  inviteYourPeople: "Invite your people",
  shareThisConnectWithAFriend: "Share this Connect with a friend.",
  connectLink: "Connect link",
  copyLink: "Copy link",
  unlimited: "unlimited",
  pending: "pending",
  waitlist: "waitlist",
} as const
