export const discoverPageCopy = {
  anyTime: "Any time",
  any: "Any",
  when: "When",
  anytime: "Anytime",
  today: "Today",
  tomorrow: "Tomorrow",
  thisWeek: "This week",
  skillLevel: "Skill level",
  beginner: "Beginner",
  intermediate: "Intermediate",
  advanced: "Advanced",
  ageGroups: "Age groups",
  cost: "Cost",
  free: "Free",
  splitCost: "Split cost",
  payYourOwn: "Pay your own",
  ticketed: "Ticketed",
  everyone: "Everyone",
  discoverConnects: "Discover Connects",
  categoryFilters: "Category filters",
  allCategories: "All categories",
  within: "Within ",
  colonSeparator: ":",
  connectsNearby: " Connects nearby",
  locationSymbol: "\u2316",
  florentin: "Florentin",
  spacedMiddleDotSeparator: " \u00b7 ",
  kilometersSuffix: " km",
  removeFilter: (key: string | number) => "Remove " + String(key) + " filter",
  removeSymbol: "\u00d7",
  clearAll: "Clear all",
  hasSpotsOpen: "Has spots open",
  filters: "Filters",
  sort: "Sort by:",
  sortConnects: "Sort Connects",
  distance: "Distance",
  relevance: "Relevance",
  popularity: "Popularity",
  relevanceHint: "Prioritizes matches to your search and selected interests.",
  ageAdult: "18+",
  age18to25: "18-25",
  age25to35: "25-35",
  age35Plus: "35+",
  hideMap: "Hide map",
  showMap: "Show map",
  reload: "Reload",
  reset: "Reset",
  kmOf: " km of ",
  text1Km: "1 km",
  text100Km: "100 km",
  showConnects: "Show Connects",
  refreshingConnects: "Refreshing Connects",
  startingSoonNearYou: "Starting soon near you",
  inTheNextFewHoursNearbyOrOnline: "In the next few hours \u00b7 nearby or online",
  spotsLeft: (value: string | number) => "" + String(value) + " spots left",
  nothingPinnedHereYet: "Nothing pinned here yet.",
  hostAConnect: "Host a Connect",
  clearFilters: "Clear filters",
  tryAWiderRadiusAnotherCategoryOrADifferent: "Try a wider radius, another category, or a different time. The next plan could be yours.",
  locations: " locations",
  hideList: "Hide list",
  showList: "Show list",
  saveYourSpotIn: (title: string | number) => "Save your spot in " + String(title) + "",
  youHaveBeenBrowsingAsAGuestWhichIs: "You have been browsing as a guest, which is fine. ",
  justNeedsANameToExpectAtTheGate: " just needs a name to expect at the gate. Sign up and you will land back here.",
  signUpAndJoin: "Sign up and join",
  iHaveAnAccount: "I have an account",
  whereShouldWeLook: "Where should we look?",
  searchThisArea: "Search this area",
  preciseSearchCoordinatesStayInMemoryNotInThe: "Precise search coordinates stay in memory, not in the URL.",
  joined: "Joined \u2713",
  requestSent: "Request sent",
  waitlisted: "Waitlisted",
  joinWaitlist: "Join waitlist",
  requestToJoin: "Request to join",
  join: "Join",
  startingSoon: "Starting soon",
  hostApproves: "Host approves",
  openToEveryone: "Open to everyone",
  everyoneWelcome: "Everyone welcome",
  checkmarkSymbol: "\u2713",
  verified: " Verified",
  starSymbol: "\u2605",
  hosted: " hosted \u00b7 ",
  attendance: "% attendance",
  approx: " (approx.)",
  commaSeparatorWithSpace: ", ",
  going: (attendeeCount: string | number) => "" + String(attendeeCount) + " going",
} as const
